/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./../../lib/context"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CircleCreateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['CircleWhereUniqueInput'][] | null; // [CircleWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CircleCreateOrConnectWithoutUserInput'][] | null; // [CircleCreateOrConnectWithoutUserInput!]
    create?: NexusGenInputs['CircleCreateWithoutUserInput'][] | null; // [CircleCreateWithoutUserInput!]
  }
  CircleCreateOrConnectWithoutUserInput: { // input type
    create: NexusGenInputs['CircleCreateWithoutUserInput']; // CircleCreateWithoutUserInput!
    where: NexusGenInputs['CircleWhereUniqueInput']; // CircleWhereUniqueInput!
  }
  CircleCreateWithoutUserInput: { // input type
    memberCount: number; // Int!
    picUrl: string; // String!
    title: string; // String!
  }
  CircleScalarWhereInput: { // input type
    AND?: NexusGenInputs['CircleScalarWhereInput'][] | null; // [CircleScalarWhereInput!]
    NOT?: NexusGenInputs['CircleScalarWhereInput'][] | null; // [CircleScalarWhereInput!]
    OR?: NexusGenInputs['CircleScalarWhereInput'][] | null; // [CircleScalarWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    memberCount?: NexusGenInputs['IntFilter'] | null; // IntFilter
    picUrl?: NexusGenInputs['StringFilter'] | null; // StringFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    userId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  CircleUpdateManyMutationInput: { // input type
    memberCount?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    picUrl?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CircleUpdateManyWithWhereWithoutUserInput: { // input type
    data: NexusGenInputs['CircleUpdateManyMutationInput']; // CircleUpdateManyMutationInput!
    where: NexusGenInputs['CircleScalarWhereInput']; // CircleScalarWhereInput!
  }
  CircleUpdateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['CircleWhereUniqueInput'][] | null; // [CircleWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CircleCreateOrConnectWithoutUserInput'][] | null; // [CircleCreateOrConnectWithoutUserInput!]
    create?: NexusGenInputs['CircleCreateWithoutUserInput'][] | null; // [CircleCreateWithoutUserInput!]
    delete?: NexusGenInputs['CircleWhereUniqueInput'][] | null; // [CircleWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CircleScalarWhereInput'][] | null; // [CircleScalarWhereInput!]
    disconnect?: NexusGenInputs['CircleWhereUniqueInput'][] | null; // [CircleWhereUniqueInput!]
    set?: NexusGenInputs['CircleWhereUniqueInput'][] | null; // [CircleWhereUniqueInput!]
    update?: NexusGenInputs['CircleUpdateWithWhereUniqueWithoutUserInput'][] | null; // [CircleUpdateWithWhereUniqueWithoutUserInput!]
    updateMany?: NexusGenInputs['CircleUpdateManyWithWhereWithoutUserInput'][] | null; // [CircleUpdateManyWithWhereWithoutUserInput!]
    upsert?: NexusGenInputs['CircleUpsertWithWhereUniqueWithoutUserInput'][] | null; // [CircleUpsertWithWhereUniqueWithoutUserInput!]
  }
  CircleUpdateWithWhereUniqueWithoutUserInput: { // input type
    data: NexusGenInputs['CircleUpdateWithoutUserInput']; // CircleUpdateWithoutUserInput!
    where: NexusGenInputs['CircleWhereUniqueInput']; // CircleWhereUniqueInput!
  }
  CircleUpdateWithoutUserInput: { // input type
    memberCount?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    picUrl?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CircleUpsertWithWhereUniqueWithoutUserInput: { // input type
    create: NexusGenInputs['CircleCreateWithoutUserInput']; // CircleCreateWithoutUserInput!
    update: NexusGenInputs['CircleUpdateWithoutUserInput']; // CircleUpdateWithoutUserInput!
    where: NexusGenInputs['CircleWhereUniqueInput']; // CircleWhereUniqueInput!
  }
  CircleWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  CommentCreateInput: { // input type
    Post?: NexusGenInputs['PostCreateOneWithoutCommentsInput'] | null; // PostCreateOneWithoutCommentsInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutCommentInput'] | null; // InteractCreateOneWithoutCommentInput
    text: string; // String!
    toUid?: number | null; // Int
    user?: NexusGenInputs['UserCreateOneWithoutCommentInput'] | null; // UserCreateOneWithoutCommentInput
  }
  CommentCreateManyWithoutInteractInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutinteractInput'][] | null; // [CommentCreateOrConnectWithoutinteractInput!]
    create?: NexusGenInputs['CommentCreateWithoutInteractInput'][] | null; // [CommentCreateWithoutInteractInput!]
  }
  CommentCreateManyWithoutPostInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutPostInput'][] | null; // [CommentCreateOrConnectWithoutPostInput!]
    create?: NexusGenInputs['CommentCreateWithoutPostInput'][] | null; // [CommentCreateWithoutPostInput!]
  }
  CommentCreateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutuserInput'][] | null; // [CommentCreateOrConnectWithoutuserInput!]
    create?: NexusGenInputs['CommentCreateWithoutUserInput'][] | null; // [CommentCreateWithoutUserInput!]
  }
  CommentCreateOrConnectWithoutPostInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutPostInput']; // CommentCreateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateOrConnectWithoutinteractInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutInteractInput']; // CommentCreateWithoutInteractInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateOrConnectWithoutuserInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutUserInput']; // CommentCreateWithoutUserInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateWithoutInteractInput: { // input type
    Post?: NexusGenInputs['PostCreateOneWithoutCommentsInput'] | null; // PostCreateOneWithoutCommentsInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    text: string; // String!
    toUid?: number | null; // Int
    user?: NexusGenInputs['UserCreateOneWithoutCommentInput'] | null; // UserCreateOneWithoutCommentInput
  }
  CommentCreateWithoutPostInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutCommentInput'] | null; // InteractCreateOneWithoutCommentInput
    text: string; // String!
    toUid?: number | null; // Int
    user?: NexusGenInputs['UserCreateOneWithoutCommentInput'] | null; // UserCreateOneWithoutCommentInput
  }
  CommentCreateWithoutUserInput: { // input type
    Post?: NexusGenInputs['PostCreateOneWithoutCommentsInput'] | null; // PostCreateOneWithoutCommentsInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutCommentInput'] | null; // InteractCreateOneWithoutCommentInput
    text: string; // String!
    toUid?: number | null; // Int
  }
  CommentScalarWhereInput: { // input type
    AND?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    NOT?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    OR?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    interactId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    postId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    text?: NexusGenInputs['StringFilter'] | null; // StringFilter
    toUid?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    userId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  CommentUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    toUid?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
  }
  CommentUpdateManyWithWhereWithoutInteractInput: { // input type
    data: NexusGenInputs['CommentUpdateManyMutationInput']; // CommentUpdateManyMutationInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithWhereWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUpdateManyMutationInput']; // CommentUpdateManyMutationInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithWhereWithoutUserInput: { // input type
    data: NexusGenInputs['CommentUpdateManyMutationInput']; // CommentUpdateManyMutationInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithoutInteractInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutinteractInput'][] | null; // [CommentCreateOrConnectWithoutinteractInput!]
    create?: NexusGenInputs['CommentCreateWithoutInteractInput'][] | null; // [CommentCreateWithoutInteractInput!]
    delete?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    disconnect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    set?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    update?: NexusGenInputs['CommentUpdateWithWhereUniqueWithoutInteractInput'][] | null; // [CommentUpdateWithWhereUniqueWithoutInteractInput!]
    updateMany?: NexusGenInputs['CommentUpdateManyWithWhereWithoutInteractInput'][] | null; // [CommentUpdateManyWithWhereWithoutInteractInput!]
    upsert?: NexusGenInputs['CommentUpsertWithWhereUniqueWithoutInteractInput'][] | null; // [CommentUpsertWithWhereUniqueWithoutInteractInput!]
  }
  CommentUpdateManyWithoutPostInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutPostInput'][] | null; // [CommentCreateOrConnectWithoutPostInput!]
    create?: NexusGenInputs['CommentCreateWithoutPostInput'][] | null; // [CommentCreateWithoutPostInput!]
    delete?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    disconnect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    set?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    update?: NexusGenInputs['CommentUpdateWithWhereUniqueWithoutPostInput'][] | null; // [CommentUpdateWithWhereUniqueWithoutPostInput!]
    updateMany?: NexusGenInputs['CommentUpdateManyWithWhereWithoutPostInput'][] | null; // [CommentUpdateManyWithWhereWithoutPostInput!]
    upsert?: NexusGenInputs['CommentUpsertWithWhereUniqueWithoutPostInput'][] | null; // [CommentUpsertWithWhereUniqueWithoutPostInput!]
  }
  CommentUpdateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutuserInput'][] | null; // [CommentCreateOrConnectWithoutuserInput!]
    create?: NexusGenInputs['CommentCreateWithoutUserInput'][] | null; // [CommentCreateWithoutUserInput!]
    delete?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    disconnect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    set?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    update?: NexusGenInputs['CommentUpdateWithWhereUniqueWithoutUserInput'][] | null; // [CommentUpdateWithWhereUniqueWithoutUserInput!]
    updateMany?: NexusGenInputs['CommentUpdateManyWithWhereWithoutUserInput'][] | null; // [CommentUpdateManyWithWhereWithoutUserInput!]
    upsert?: NexusGenInputs['CommentUpsertWithWhereUniqueWithoutUserInput'][] | null; // [CommentUpsertWithWhereUniqueWithoutUserInput!]
  }
  CommentUpdateWithWhereUniqueWithoutInteractInput: { // input type
    data: NexusGenInputs['CommentUpdateWithoutInteractInput']; // CommentUpdateWithoutInteractInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithWhereUniqueWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUpdateWithoutPostInput']; // CommentUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithWhereUniqueWithoutUserInput: { // input type
    data: NexusGenInputs['CommentUpdateWithoutUserInput']; // CommentUpdateWithoutUserInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithoutInteractInput: { // input type
    Post?: NexusGenInputs['PostUpdateOneWithoutCommentsInput'] | null; // PostUpdateOneWithoutCommentsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    toUid?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneWithoutCommentInput'] | null; // UserUpdateOneWithoutCommentInput
  }
  CommentUpdateWithoutPostInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    interact?: NexusGenInputs['InteractUpdateOneWithoutCommentInput'] | null; // InteractUpdateOneWithoutCommentInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    toUid?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneWithoutCommentInput'] | null; // UserUpdateOneWithoutCommentInput
  }
  CommentUpdateWithoutUserInput: { // input type
    Post?: NexusGenInputs['PostUpdateOneWithoutCommentsInput'] | null; // PostUpdateOneWithoutCommentsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    interact?: NexusGenInputs['InteractUpdateOneWithoutCommentInput'] | null; // InteractUpdateOneWithoutCommentInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    toUid?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
  }
  CommentUpsertWithWhereUniqueWithoutInteractInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutInteractInput']; // CommentCreateWithoutInteractInput!
    update: NexusGenInputs['CommentUpdateWithoutInteractInput']; // CommentUpdateWithoutInteractInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpsertWithWhereUniqueWithoutPostInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutPostInput']; // CommentCreateWithoutPostInput!
    update: NexusGenInputs['CommentUpdateWithoutPostInput']; // CommentUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpsertWithWhereUniqueWithoutUserInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutUserInput']; // CommentCreateWithoutUserInput!
    update: NexusGenInputs['CommentUpdateWithoutUserInput']; // CommentUpdateWithoutUserInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  InteractCreateOneWithoutCommentInput: { // input type
    connect?: NexusGenInputs['InteractWhereUniqueInput'] | null; // InteractWhereUniqueInput
    connectOrCreate?: NexusGenInputs['InteractCreateOrConnectWithoutCommentInput'] | null; // InteractCreateOrConnectWithoutCommentInput
    create?: NexusGenInputs['InteractCreateWithoutCommentInput'] | null; // InteractCreateWithoutCommentInput
  }
  InteractCreateOneWithoutPostInput: { // input type
    connect?: NexusGenInputs['InteractWhereUniqueInput'] | null; // InteractWhereUniqueInput
    connectOrCreate?: NexusGenInputs['InteractCreateOrConnectWithoutPostInput'] | null; // InteractCreateOrConnectWithoutPostInput
    create?: NexusGenInputs['InteractCreateWithoutPostInput'] | null; // InteractCreateWithoutPostInput
  }
  InteractCreateOrConnectWithoutCommentInput: { // input type
    create: NexusGenInputs['InteractCreateWithoutCommentInput']; // InteractCreateWithoutCommentInput!
    where: NexusGenInputs['InteractWhereUniqueInput']; // InteractWhereUniqueInput!
  }
  InteractCreateOrConnectWithoutPostInput: { // input type
    create: NexusGenInputs['InteractCreateWithoutPostInput']; // InteractCreateWithoutPostInput!
    where: NexusGenInputs['InteractWhereUniqueInput']; // InteractWhereUniqueInput!
  }
  InteractCreateWithoutCommentInput: { // input type
    Post?: NexusGenInputs['PostCreateManyWithoutInteractInput'] | null; // PostCreateManyWithoutInteractInput
    againstCount?: number | null; // Int
    commentId?: number | null; // Int
    handCount?: number | null; // Int
    handUid?: string | null; // String
    hateCount?: number | null; // Int
    hateUid?: string | null; // String
    interestCount?: number | null; // Int
    interestUid?: string | null; // String
    postId?: number | null; // Int
    thinkCount?: number | null; // Int
    thinkUid?: string | null; // String
    valueCount?: number | null; // Int
    valueUid?: string | null; // String
  }
  InteractCreateWithoutPostInput: { // input type
    Comment?: NexusGenInputs['CommentCreateManyWithoutInteractInput'] | null; // CommentCreateManyWithoutInteractInput
    againstCount?: number | null; // Int
    commentId?: number | null; // Int
    handCount?: number | null; // Int
    handUid?: string | null; // String
    hateCount?: number | null; // Int
    hateUid?: string | null; // String
    interestCount?: number | null; // Int
    interestUid?: string | null; // String
    postId?: number | null; // Int
    thinkCount?: number | null; // Int
    thinkUid?: string | null; // String
    valueCount?: number | null; // Int
    valueUid?: string | null; // String
  }
  InteractUpdateOneWithoutCommentInput: { // input type
    connect?: NexusGenInputs['InteractWhereUniqueInput'] | null; // InteractWhereUniqueInput
    connectOrCreate?: NexusGenInputs['InteractCreateOrConnectWithoutCommentInput'] | null; // InteractCreateOrConnectWithoutCommentInput
    create?: NexusGenInputs['InteractCreateWithoutCommentInput'] | null; // InteractCreateWithoutCommentInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['InteractUpdateWithoutCommentInput'] | null; // InteractUpdateWithoutCommentInput
    upsert?: NexusGenInputs['InteractUpsertWithoutCommentInput'] | null; // InteractUpsertWithoutCommentInput
  }
  InteractUpdateOneWithoutPostInput: { // input type
    connect?: NexusGenInputs['InteractWhereUniqueInput'] | null; // InteractWhereUniqueInput
    connectOrCreate?: NexusGenInputs['InteractCreateOrConnectWithoutPostInput'] | null; // InteractCreateOrConnectWithoutPostInput
    create?: NexusGenInputs['InteractCreateWithoutPostInput'] | null; // InteractCreateWithoutPostInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['InteractUpdateWithoutPostInput'] | null; // InteractUpdateWithoutPostInput
    upsert?: NexusGenInputs['InteractUpsertWithoutPostInput'] | null; // InteractUpsertWithoutPostInput
  }
  InteractUpdateWithoutCommentInput: { // input type
    Post?: NexusGenInputs['PostUpdateManyWithoutInteractInput'] | null; // PostUpdateManyWithoutInteractInput
    againstCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    commentId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    handCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    handUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    hateCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    hateUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    interestCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    interestUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    postId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    thinkCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    thinkUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    valueCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    valueUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  InteractUpdateWithoutPostInput: { // input type
    Comment?: NexusGenInputs['CommentUpdateManyWithoutInteractInput'] | null; // CommentUpdateManyWithoutInteractInput
    againstCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    commentId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    handCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    handUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    hateCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    hateUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    interestCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    interestUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    postId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    thinkCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    thinkUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    valueCount?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    valueUid?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  InteractUpsertWithoutCommentInput: { // input type
    create: NexusGenInputs['InteractCreateWithoutCommentInput']; // InteractCreateWithoutCommentInput!
    update: NexusGenInputs['InteractUpdateWithoutCommentInput']; // InteractUpdateWithoutCommentInput!
  }
  InteractUpsertWithoutPostInput: { // input type
    create: NexusGenInputs['InteractCreateWithoutPostInput']; // InteractCreateWithoutPostInput!
    update: NexusGenInputs['InteractUpdateWithoutPostInput']; // InteractUpdateWithoutPostInput!
  }
  InteractWhereUniqueInput: { // input type
    commentId?: number | null; // Int
    id?: number | null; // Int
    postId?: number | null; // Int
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableIntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  PostCreateInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutPostInput'] | null; // InteractCreateOneWithoutPostInput
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  PostCreateManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutauthorInput'][] | null; // [PostCreateOrConnectWithoutauthorInput!]
    create?: NexusGenInputs['PostCreateWithoutAuthorInput'][] | null; // [PostCreateWithoutAuthorInput!]
  }
  PostCreateManyWithoutInteractInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutinteractInput'][] | null; // [PostCreateOrConnectWithoutinteractInput!]
    create?: NexusGenInputs['PostCreateWithoutInteractInput'][] | null; // [PostCreateWithoutInteractInput!]
  }
  PostCreateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostCreateWithoutCommentsInput'] | null; // PostCreateWithoutCommentsInput
  }
  PostCreateOrConnectWithoutauthorInput: { // input type
    create: NexusGenInputs['PostCreateWithoutAuthorInput']; // PostCreateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutcommentsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCommentsInput']; // PostCreateWithoutCommentsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutinteractInput: { // input type
    create: NexusGenInputs['PostCreateWithoutInteractInput']; // PostCreateWithoutInteractInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutPostInput'] | null; // InteractCreateOneWithoutPostInput
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  PostCreateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    interact?: NexusGenInputs['InteractCreateOneWithoutPostInput'] | null; // InteractCreateOneWithoutPostInput
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  PostCreateWithoutInteractInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  PostScalarWhereInput: { // input type
    AND?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    NOT?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    OR?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    content?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    interactId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  PostUpdateInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    interact?: NexusGenInputs['InteractUpdateOneWithoutPostInput'] | null; // InteractUpdateOneWithoutPostInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PostUpdateManyMutationInput: { // input type
    content?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PostUpdateManyWithWhereWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithWhereWithoutInteractInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutauthorInput'][] | null; // [PostCreateOrConnectWithoutauthorInput!]
    create?: NexusGenInputs['PostCreateWithoutAuthorInput'][] | null; // [PostCreateWithoutAuthorInput!]
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutAuthorInput'][] | null; // [PostUpdateWithWhereUniqueWithoutAuthorInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutAuthorInput'][] | null; // [PostUpdateManyWithWhereWithoutAuthorInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutAuthorInput'][] | null; // [PostUpsertWithWhereUniqueWithoutAuthorInput!]
  }
  PostUpdateManyWithoutInteractInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutinteractInput'][] | null; // [PostCreateOrConnectWithoutinteractInput!]
    create?: NexusGenInputs['PostCreateWithoutInteractInput'][] | null; // [PostCreateWithoutInteractInput!]
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutInteractInput'][] | null; // [PostUpdateWithWhereUniqueWithoutInteractInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutInteractInput'][] | null; // [PostUpdateManyWithWhereWithoutInteractInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutInteractInput'][] | null; // [PostUpsertWithWhereUniqueWithoutInteractInput!]
  }
  PostUpdateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostCreateWithoutCommentsInput'] | null; // PostCreateWithoutCommentsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['PostUpdateWithoutCommentsInput'] | null; // PostUpdateWithoutCommentsInput
    upsert?: NexusGenInputs['PostUpsertWithoutCommentsInput'] | null; // PostUpsertWithoutCommentsInput
  }
  PostUpdateWithWhereUniqueWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutAuthorInput']; // PostUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithWhereUniqueWithoutInteractInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutInteractInput']; // PostUpdateWithoutInteractInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    interact?: NexusGenInputs['InteractUpdateOneWithoutPostInput'] | null; // InteractUpdateOneWithoutPostInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PostUpdateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    content?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    interact?: NexusGenInputs['InteractUpdateOneWithoutPostInput'] | null; // InteractUpdateOneWithoutPostInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PostUpdateWithoutInteractInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PostUpsertWithWhereUniqueWithoutAuthorInput: { // input type
    create: NexusGenInputs['PostCreateWithoutAuthorInput']; // PostCreateWithoutAuthorInput!
    update: NexusGenInputs['PostUpdateWithoutAuthorInput']; // PostUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithWhereUniqueWithoutInteractInput: { // input type
    create: NexusGenInputs['PostCreateWithoutInteractInput']; // PostCreateWithoutInteractInput!
    update: NexusGenInputs['PostUpdateWithoutInteractInput']; // PostUpdateWithoutInteractInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithoutCommentsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCommentsInput']; // PostCreateWithoutCommentsInput!
    update: NexusGenInputs['PostUpdateWithoutCommentsInput']; // PostUpdateWithoutCommentsInput!
  }
  PostWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  QueryPostsOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserCreateInput: { // input type
    Comment?: NexusGenInputs['CommentCreateManyWithoutUserInput'] | null; // CommentCreateManyWithoutUserInput
    avatarUrl?: string | null; // String
    circles?: NexusGenInputs['CircleCreateManyWithoutUserInput'] | null; // CircleCreateManyWithoutUserInput
    email: string; // String!
    hatePostIds?: string | null; // String
    interestPostIds?: string | null; // String
    name?: string | null; // String
    password?: string | null; // String
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
    uuid: string; // String!
    valuePostIds?: string | null; // String
  }
  UserCreateOneWithoutCommentInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutCommentInput'] | null; // UserCreateOrConnectWithoutCommentInput
    create?: NexusGenInputs['UserCreateWithoutCommentInput'] | null; // UserCreateWithoutCommentInput
  }
  UserCreateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserCreateWithoutPostsInput'] | null; // UserCreateWithoutPostsInput
  }
  UserCreateOrConnectWithoutCommentInput: { // input type
    create: NexusGenInputs['UserCreateWithoutCommentInput']; // UserCreateWithoutCommentInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutpostsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPostsInput']; // UserCreateWithoutPostsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutCommentInput: { // input type
    avatarUrl?: string | null; // String
    circles?: NexusGenInputs['CircleCreateManyWithoutUserInput'] | null; // CircleCreateManyWithoutUserInput
    email: string; // String!
    hatePostIds?: string | null; // String
    interestPostIds?: string | null; // String
    name?: string | null; // String
    password?: string | null; // String
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
    uuid: string; // String!
    valuePostIds?: string | null; // String
  }
  UserCreateWithoutPostsInput: { // input type
    Comment?: NexusGenInputs['CommentCreateManyWithoutUserInput'] | null; // CommentCreateManyWithoutUserInput
    avatarUrl?: string | null; // String
    circles?: NexusGenInputs['CircleCreateManyWithoutUserInput'] | null; // CircleCreateManyWithoutUserInput
    email: string; // String!
    hatePostIds?: string | null; // String
    interestPostIds?: string | null; // String
    name?: string | null; // String
    password?: string | null; // String
    uuid: string; // String!
    valuePostIds?: string | null; // String
  }
  UserUpdateInput: { // input type
    Comment?: NexusGenInputs['CommentUpdateManyWithoutUserInput'] | null; // CommentUpdateManyWithoutUserInput
    avatarUrl?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    circles?: NexusGenInputs['CircleUpdateManyWithoutUserInput'] | null; // CircleUpdateManyWithoutUserInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    hatePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    interestPostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
    uuid?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    valuePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  UserUpdateOneWithoutCommentInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutCommentInput'] | null; // UserCreateOrConnectWithoutCommentInput
    create?: NexusGenInputs['UserCreateWithoutCommentInput'] | null; // UserCreateWithoutCommentInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserUpdateWithoutCommentInput'] | null; // UserUpdateWithoutCommentInput
    upsert?: NexusGenInputs['UserUpsertWithoutCommentInput'] | null; // UserUpsertWithoutCommentInput
  }
  UserUpdateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserCreateWithoutPostsInput'] | null; // UserCreateWithoutPostsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserUpdateWithoutPostsInput'] | null; // UserUpdateWithoutPostsInput
    upsert?: NexusGenInputs['UserUpsertWithoutPostsInput'] | null; // UserUpsertWithoutPostsInput
  }
  UserUpdateWithoutCommentInput: { // input type
    avatarUrl?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    circles?: NexusGenInputs['CircleUpdateManyWithoutUserInput'] | null; // CircleUpdateManyWithoutUserInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    hatePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    interestPostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
    uuid?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    valuePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  UserUpdateWithoutPostsInput: { // input type
    Comment?: NexusGenInputs['CommentUpdateManyWithoutUserInput'] | null; // CommentUpdateManyWithoutUserInput
    avatarUrl?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    circles?: NexusGenInputs['CircleUpdateManyWithoutUserInput'] | null; // CircleUpdateManyWithoutUserInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    hatePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    interestPostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    uuid?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    valuePostIds?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  UserUpsertWithoutCommentInput: { // input type
    create: NexusGenInputs['UserCreateWithoutCommentInput']; // UserCreateWithoutCommentInput!
    update: NexusGenInputs['UserUpdateWithoutCommentInput']; // UserUpdateWithoutCommentInput!
  }
  UserUpsertWithoutPostsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPostsInput']; // UserCreateWithoutPostsInput!
    update: NexusGenInputs['UserUpdateWithoutPostsInput']; // UserUpdateWithoutPostsInput!
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
    uuid?: string | null; // String
  }
}

export interface NexusGenEnums {
  InteractAction: "against" | "hand" | "hate" | "interest" | "think" | "value"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
}

export interface NexusGenObjects {
  AuthPayLoad: { // root type
    code?: number | null; // Int
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Comment: { // root type
    id?: number | null; // Int
    postId?: number | null; // Int
    text?: string | null; // String
    toUid?: number | null; // Int
    userId?: number | null; // Int
  }
  Interact: { // root type
    againstCount?: number | null; // Int
    commentId?: number | null; // Int
    handCount?: number | null; // Int
    hateCount?: number | null; // Int
    id?: number | null; // Int
    interestCount?: number | null; // Int
    postId?: number | null; // Int
    thinkCount?: number | null; // Int
    valueCount?: number | null; // Int
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: number | null; // Int
    hasNextPage?: boolean | null; // Boolean
  }
  Post: { // root type
    authorId?: string | null; // String
    content: string; // String!
    createdAt?: NexusGenScalars['Date'] | null; // Date
    id: number; // Int!
    title?: string | null; // String
  }
  Query: {};
  QueryResponse: { // root type
    edges?: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    pageInfo?: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
  User: { // root type
    avatarUrl?: string | null; // String
    email?: string | null; // String
    id?: number | null; // Int
    name?: string | null; // String
    password?: string | null; // String
    uuid?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayLoad: { // field return type
    code: number | null; // Int
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Comment: { // field return type
    id: number | null; // Int
    interact: NexusGenRootTypes['Interact'] | null; // Interact
    postId: number | null; // Int
    text: string | null; // String
    toUid: number | null; // Int
    toUser: NexusGenRootTypes['User'] | null; // User
    user: NexusGenRootTypes['User'] | null; // User
    userId: number | null; // Int
  }
  Interact: { // field return type
    againstCount: number | null; // Int
    commentId: number | null; // Int
    handCount: number | null; // Int
    hateCount: number | null; // Int
    id: number | null; // Int
    interestCount: number | null; // Int
    postId: number | null; // Int
    thinkCount: number | null; // Int
    valueCount: number | null; // Int
  }
  Mutation: { // field return type
    createNewPost: NexusGenRootTypes['Post'] | null; // Post
    createNewUser: NexusGenRootTypes['AuthPayLoad'] | null; // AuthPayLoad
    createOneComment: NexusGenRootTypes['Comment']; // Comment!
    createOnePost: NexusGenRootTypes['Post']; // Post!
    createOneUser: NexusGenRootTypes['User']; // User!
    deleteOnePost: NexusGenRootTypes['Post'] | null; // Post
    interactCommentMutation: NexusGenRootTypes['Interact'] | null; // Interact
    interactMutation: NexusGenRootTypes['Interact'] | null; // Interact
    login: NexusGenRootTypes['AuthPayLoad'] | null; // AuthPayLoad
    upsertOnePost: NexusGenRootTypes['Post']; // Post!
    upsertOneUser: NexusGenRootTypes['User']; // User!
  }
  PageInfo: { // field return type
    endCursor: number | null; // Int
    hasNextPage: boolean | null; // Boolean
  }
  Post: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    authorId: string | null; // String
    comments: Array<NexusGenRootTypes['Comment'] | null> | null; // [Comment]
    commentsTotalCount: number | null; // Int
    content: string; // String!
    createdAt: NexusGenScalars['Date'] | null; // Date
    id: number; // Int!
    interact: NexusGenRootTypes['Interact'] | null; // Interact
    title: string | null; // String
  }
  Query: { // field return type
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    interact: NexusGenRootTypes['Interact'] | null; // Interact
    post: NexusGenRootTypes['Post'] | null; // Post
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    postsQuery: NexusGenRootTypes['QueryResponse'] | null; // QueryResponse
    user: NexusGenRootTypes['User'] | null; // User
  }
  QueryResponse: { // field return type
    edges: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    pageInfo: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
  User: { // field return type
    avatarUrl: string | null; // String
    email: string | null; // String
    id: number | null; // Int
    name: string | null; // String
    password: string | null; // String
    posts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    uuid: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayLoad: { // field return type name
    code: 'Int'
    token: 'String'
    user: 'User'
  }
  Comment: { // field return type name
    id: 'Int'
    interact: 'Interact'
    postId: 'Int'
    text: 'String'
    toUid: 'Int'
    toUser: 'User'
    user: 'User'
    userId: 'Int'
  }
  Interact: { // field return type name
    againstCount: 'Int'
    commentId: 'Int'
    handCount: 'Int'
    hateCount: 'Int'
    id: 'Int'
    interestCount: 'Int'
    postId: 'Int'
    thinkCount: 'Int'
    valueCount: 'Int'
  }
  Mutation: { // field return type name
    createNewPost: 'Post'
    createNewUser: 'AuthPayLoad'
    createOneComment: 'Comment'
    createOnePost: 'Post'
    createOneUser: 'User'
    deleteOnePost: 'Post'
    interactCommentMutation: 'Interact'
    interactMutation: 'Interact'
    login: 'AuthPayLoad'
    upsertOnePost: 'Post'
    upsertOneUser: 'User'
  }
  PageInfo: { // field return type name
    endCursor: 'Int'
    hasNextPage: 'Boolean'
  }
  Post: { // field return type name
    author: 'User'
    authorId: 'String'
    comments: 'Comment'
    commentsTotalCount: 'Int'
    content: 'String'
    createdAt: 'Date'
    id: 'Int'
    interact: 'Interact'
    title: 'String'
  }
  Query: { // field return type name
    comments: 'Comment'
    interact: 'Interact'
    post: 'Post'
    posts: 'Post'
    postsQuery: 'QueryResponse'
    user: 'User'
  }
  QueryResponse: { // field return type name
    edges: 'Post'
    pageInfo: 'PageInfo'
  }
  User: { // field return type name
    avatarUrl: 'String'
    email: 'String'
    id: 'Int'
    name: 'String'
    password: 'String'
    posts: 'Post'
    uuid: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createNewPost: { // args
      content: string; // String!
    }
    createNewUser: { // args
      avatarUrl?: string | null; // String
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    createOneComment: { // args
      data: NexusGenInputs['CommentCreateInput']; // CommentCreateInput!
    }
    createOnePost: { // args
      data: NexusGenInputs['PostCreateInput']; // PostCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteOnePost: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    interactCommentMutation: { // args
      actionType: string; // String!
      commentId: number; // Int!
      count: number; // Int!
    }
    interactMutation: { // args
      actionType?: NexusGenEnums['InteractAction'] | null; // InteractAction
      count: number; // Int!
      postId: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
      username: string; // String!
    }
    upsertOnePost: { // args
      create: NexusGenInputs['PostCreateInput']; // PostCreateInput!
      update: NexusGenInputs['PostUpdateInput']; // PostUpdateInput!
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    upsertOneUser: { // args
      create: NexusGenInputs['UserCreateInput']; // UserCreateInput!
      update: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Query: {
    comments: { // args
      after?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      before?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    interact: { // args
      where: NexusGenInputs['InteractWhereUniqueInput']; // InteractWhereUniqueInput!
    }
    post: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryPostsOrderByInput'][] | null; // [QueryPostsOrderByInput!]
    }
    postsQuery: { // args
      cursor?: number | null; // Int
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}